---
title: "lab2_homework"
author: "Nicholas Nagle"
date: "February 2, 2015"
output: pdf_document
---

# Part 1. Analysis of El Malpais data

What do the tree ring data tell us about monthly precipitation?

Write up a short report (~ 2 paragraphs) answering the following questions:

- Describe the monthly rainfall pattern.  
- During what months is tree ring width correlated with rainfall?
- How appropriate is (linear) correlation as a description of the relationship between tree ring width and monthly rainfall?
- If you had to create a 12 month period that was correlated with tree ring width, what 12 months would those be?

In answering these questions, I want to see:

 - A bar chart or line graph showing average rainfall each month.
 - Two scatterplots of tree ring width and precipitation, one with the current January, and one with the current August.  Use these to assess whether the relationship is approximately linear or not at all linear.
 - Two (or one) plots showing the correlation at every month between tree ring width and precipitation, for both the current year and the previous year.  If you can get both current and previous (lagged) year on one plot, then great.
 
 Make sure that your charts are properly labeled and are referred to in your answer.
 
```{r}
library(dplyr)
library(ggplot2)
library(magrittr)
library(tidyr)
setwd("~/Desktop/Quantitative Methods in Geography/415Repository/homework2/data")
precip <- read.csv('precip.csv')
rwi <- read.csv('rwi.csv')
temp.data <- gather(data=precip, key=month, value=precip, -year)
tidy.precip <- arrange(temp.data, year, month)
tidy.precip$precip[tidy.precip$precip<0]<-NA
tidy.precip %>% group_by(month) %>%summarize(precip=mean(precip, na.rm=TRUE)) %>%ggplot(data=., aes(month, precip)) + geom_bar(stat='identity') + labs(y='Precipitation (in)',title='Monthly Precip')
rwi.precip <- left_join(precip, rwi, by='year')
ggplot(data=rwi.precip,aes(rwi,Jan))+geom_point(stat='identity')+labs(y='Jan Precip (in)',x='Tree Ring Width',title='January')
ggplot(data=rwi.precip,aes(rwi,Aug))+geom_point(stat='identity')+labs(y='Aug Precip (in)',x='Tree Ring Width',title='August')
rwi.precip2<-left_join(rwi,tidy.precip,by='year')%>%filter(year>=1895)
precip.cors<-rwi.precip2%>%group_by(month)%>%summarise(r=cor(rwi,precip))
lagprecip.cors<-rwi.precip2%>%group_by(month)%>%summarise(lag_r=cor(rwi,lag(precip),use='complete.obs'))
ggplot()+geom_point(data=precip.cors,aes(x=month,y=r),colour='blue')+geom_point(data=lagprecip.cors,aes(x=month,y=lag_r),colour='red')+ylab('Blue=current r, Red=lagged r')+labs(title='Monthly Correlation')
```
  Referring to the chart "Monthly Precip," it is apparent that rainfall peaks during the summer months at this location.  Rainfall is at a minimum during the spring and relatively consistent at around 1 in for autumn and winter.  The "Monthly Correlation" chart shows that ring width is most strongly correlated with rainfall during the first half of the year (Jan-Jun.)  Intuitively this makes sense because these months encompass the growing season.  To determine whether a linear correlation is appropriate, the "January" and "August" scatter plots are useful.  While a strong linear correlation is not apparent (esp for August,) it certainly appears more appropriate than an exponential, quadratic, or any other correlation method.
  If I were to select a 12-month period that was correlated with tree growth I would choose the entire lagged year.  The strongest correlations of all occur during the first half of the lagged year.  While there is a notably stronger correlation for the current year in Jul, Sep, Nov, and Dec, selecting the first half of the lagged year and the second half of the current year is not possible because they are not sequential.  In addition, the correlations are very low for the second half of the year anyways, so the higher values for the current year are still relatively insignificant, and may even be noise.  Therefore, selecting the entire lagged year will include the high r values in the first half of the year and best show the correlation between precipitation and tree ring width.

# Part 2: Getting the interpretation of correlation correct.


1. In regard to the first part, which of the following is more correct and explain.
  - A positive correlation between tree ring width and January precipitation might happen because January is often (but not always) wetter than the average month.
  - A positive correlation between tree ring width and January precipitation might happen if dryer-than-average Januarys are associate with smaller-than-average tree ring widths.
  
  By referring to the scatter plot of January Precipitation vs. Tree Ring Width, it seems like the second explanation is more correct.  The data on this plot are tighter in lower left corner, where precipitation is low and ring width is minimal.  The very wet Januarys, on the right hand side of the plot, display a variety of different ring widths.

2. 
  - Would the correlation between the age of a second-hand car and its price be positive or negative?  Why?  (Antiques are not included.)
  - How would including antique cars change your response?
  
  The correlation would be negative because as one variable increases (age,) the other decreases (price.)  If antiques were included the correlation would be non-linear.  In this case, the price would start to increase again once the car reached a certain age (reaching "antique status.")  The correlation, therefore, would be negative until this age, but then become positive, with price increasing as age increases.

3. True or False, and explain: if the correlation coefficient is 0.90, then 90% of the points are highly correlated.

This is false.  Correlation refers to how close a data point is to a line describing the average value for one variable given the other.  Therefore, an r value of 0.90 means that on the whole the points are very close to their averages.

4. An economist is studying the relationship between household income and teenage pregnancy in the United States.  She has data for each of the 50 states, showing the average household income of families with teenagers, and the rates of pregnancy among teenage girls in that state.  The correlation is 0.4.  Does this give a fair estimate of th e strength of the association between household income and teenage pregnancy?  Explain.

The main reason that calls this result into question is the MAUP.  This refers to the variability that is lost when data (such as income and teenage pregnancy rates) are aggregated, especially over large areas (such as states.)  This reduction in variability will lead to an inflated correlation coefficient.

5. Three data sets are collected and the correlation coefficient is computed in each case.  The variables in the datasets are:
  - grade point average in freshman year and sophomore year in college.
  - grade point average in freshman year and senior year in college.
  - length and weight of two-by-four boards of lumber.
  
  Possible values for correlation coefficients are: -0.5,   0.0,   0.3,  0.6,  0.95.  Match the correlations with the data sets; two will be left over.  Explain your answers.
  
  A student's intelligence will likely not change very much from year to year.  Therefore, the grades they get one year will be quite similar to the grades they get the next year, an r=0.6
  Over the course of four years, a student's grades will change more, but they will still be related, a poor student will seldom become a great student and vice-versa, an r=0.3
  The length and weight of a two-by-four are highly codependent, adding on more material (length) will definitely increase the weight by a predictable amount given the wood's density, an r=0.95

6. Studies find a negative correlation between hours spent watching television and scores on reading tests.  Does watching television make people less able to read?  Discuss briefly.

This is an example of correlation not meaning causation.  In this case, the lower scores would be due to the fact that those who watch more tv don't have as much time to study.  The cause of the low scores is less study time, not the tv that is watched in lieu of studying.